blank_issues_enabled: false
# contact_links:
#   - name: 💬 Discussions
#     url: https://github.com/asdkant/open-thumb/discussions
#     about: If you want to start a conversation, go to the discussions section
